name: AWS E2E Tests

on:
  #  push:
  #    branches:
  #      - master
  #  pull_request:
  workflow_dispatch:

jobs:
  # Runs tests on AWS that are too big for github actions
  # Tests that are small enough are above in `actions:`
  aws:
    name: AWS
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        juju: [2.9/stable]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo snap install juju --classic
        sudo snap install juju-wait --classic

    - name: Bootstrap onto AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        set -eux
        juju autoload-credentials --client aws
        juju bootstrap aws/us-east-1 uk8saws --debug --show-log --config test-mode=true --model-default test-mode=true
        juju deploy ubuntu --constraints 'instance-type=t3a.xlarge root-disk=80G'
        juju wait -vw
        juju status
        juju status --format yaml

    - name: Copy code to AWS instance
      run: |
        set -eux
        juju scp -- -r $(pwd)/ ubuntu/0:~/

    - name: Install test dependencies
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common tar
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          sudo apt install -y docker-ce
          sudo systemctl status docker
          sudo usermod -a -G docker ubuntu
        EOF

    - name: Test docker installation
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          docker
          docker run hello-world
        EOF

    - name: Install Kubectl
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          sudo curl -L "https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
          sudo chmod +x /usr/local/bin/kubectl
          kubectl version --short --client
        EOF

    - name: Install kustomize
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
          mv kustomize_3.2.0_linux_amd64 manifests/kustomize
          chmod +x manifests/kustomize
        EOF

    - name: Install KinD
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
        EOF

    - name: Create a KinD Cluster
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          cd manifests
          kind create cluster --config ./tests/gh-actions/kind-cluster.yaml
        EOF

    - name: Deploy Kubeflow
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          cd manifests
          while ! ./kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
          kubectl -n kubeflow wait --for=condition=Ready pods --all --timeout=1200s
        EOF
      timeout-minutes: 45

    - name: Test Kubeflow
      run: |
        juju ssh ubuntu/0 <<EOF
          set -eux
          cd manifests
          kubectl -n kubeflow-user-example-com create configmap e2e-test --from-file ./tests/e2e/notebook/kubeflow-e2e-mnist.ipynb
          kubectl -n kubeflow-user-example-com create -f ./tests/e2e/yamls/execute-e2e.yaml
          kubectl -n kubeflow-user-example-com wait --for=condition=complete --timeout=1200s job/test-notebook-job
        EOF
      timeout-minutes: 20

    - name: KinD get pods
      run: juju ssh ubuntu/0 kubectl get pods -A
      if: failure()

    - name: KinD describe pods
      run: juju ssh ubuntu/0 kubectl describe pods -A
      if: failure()

    - name: KinD export logs
      run: |
        set -eux
        juju ssh ubuntu/0 <<EOF
          set -eux
          kind export logs ./logs
          tar -czvf kind-logs-${{ strategy.job-index }}.tar.gz ./logs
        EOF
        juju scp ubuntu/0:~/kind-logs-${{ strategy.job-index }}.tar.gz .
      if: failure()

    - name: Upload KinD logs tarball
      uses: actions/upload-artifact@v2
      with:
        name: kind-logs-aws
        path: ./kind-logs-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Generate kubectl describe
      run: |
        set -eux
        juju ssh ubuntu/0 <<EOF
          set -eux
          mkdir describe-${{ strategy.job-index }}
          for resource in \$(kubectl api-resources -o name | sort); do
            sudo kubectl describe \$resource -A > describe-${{ strategy.job-index }}/"\$resource".describe || true
          done
          tar -cvzf describe.tar.gz describe-${{ strategy.job-index }}/*.describe
        EOF
        juju scp ubuntu/0:~/describe.tar.gz describe-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Upload kubectl describe
      uses: actions/upload-artifact@v2
      with:
        name: kubectl-describe-aws
        path: describe-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Generate kubeflow pod logs
      run: |
        set -eux
        juju ssh ubuntu/0 <<EOF
          set -eux
          mkdir stdout-${{ strategy.job-index }}
          for namespace in admin kubeflow; do
              for pod in \$(kubectl get pods -n \$namespace -o custom-columns=:metadata.name --no-headers); do
                  for container in \$(kubectl get pods -n \$namespace -o jsonpath="{.spec.containers[*].name}" \$pod); do
                    kubectl logs -n \$namespace --timestamps \$pod -c \$container > stdout-${{ strategy.job-index }}/\$namespace-\$pod-\$container.log || true
                  done
              done
          done
          tar -cvzf stdout.tar.gz stdout-${{ strategy.job-index }}/*.log
        EOF
        juju scp ubuntu/0:~/stdout.tar.gz stdout-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Upload kubeflow pod logs
      uses: actions/upload-artifact@v2
      with:
        name: kubectl-stdout-aws
        path: stdout-${{ strategy.job-index }}.tar.gz
      if: failure()

    - name: Destroy controller
      run: juju destroy-controller -y uk8saws --destroy-all-models --destroy-storage
      if: always()
